export const REQUEST_MONTLY_SIP_DATA = "REQUEST_MONTLY_SIP_DATA"
export const STORE_MONTLY_SIP_DATA = "STORE_MONTLY_SIP_DATA"
export const SHOW_SINGLE_SIP_INFO = "SHOW_SINGLE_SIP_INFO"
export const FILTER_MONTH_SELECTED = "FILTER_MONTH_SELECTED"
export const CREATE_NEW_INVESTMENT = "CREATE_NEW_INVESTMENT"

export const STORE_COMPANY_INFO = "STORE_COMPANY_INFO"
export const STORE_SCHEME_INFO = "STORE_SCHEME_INFO"

export const DASHBOARD_SELECTED_COMPANY = "DASHBOARD_SELECTED_COMPANY"
export const DASHBOARD_SELECTED_SCHEME = "DASHBOARD_SELECTED_SCHEME"
export const DASHBOARD_SCHEME_WISE_INVESTMENTS = "DASHBOARD_SCHEME_WISE_INVESTMENTS"